apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      name: postgres-pods
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
      # Add the probes here
      # livenessProbe:
      #   exec:
      #     command:
      #       - pg_isready
      #   initialDelaySeconds: 30
      #   periodSeconds: 10
      # readinessProbe:
      #   exec:
      #     command:
      #       - pg_isready
      #   initialDelaySeconds: 30
      #   periodSeconds: 10
      # # Add resource requests and limits here
      # resources:
      #   requests:
      #     memory: "1Gi"
      #     cpu: "500m"
      #   limits:
      #     memory: "2Gi"
      #     cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
