// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "@/app/globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import { Navbar } from "@/components/example/navbar";
//
// import { jwtDecode } from "jwt-decode";
// import { cookies } from "next/headers";
// import { AuthProvider } from "@/context/auth";
// import { UserProvider } from "@/context/user";
// const geistSans = localFont({
// 	src: "../fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "../fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });
//
// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
//
// export default async function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	// const cookieStore = await cookies();
// 	// const jwtToken = cookieStore.get("jwt");
// 	// let user_token;
// 	// if (jwtToken) {
// 	// 	user_token = jwtDecode<{ user_id: number | undefined }>(jwtToken?.value); // Define the expected structure
// 	// } else {
// 	// 	return null;
// 	// }
//
// 	return (
// 		<html lang="en" suppressHydrationWarning>
// 					<body
// 						className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-primary [&_*]:select-none overscroll-y-none`}
// 					>
// 							<Navbar />
// 							{children}
// 					</body>
// 		</html>
// 	);
// }

import localFont from "next/font/local";
import "@/app/globals.css";
import { Navbar } from "@/components/example/navbar";

const geistSans = localFont({ src: "../fonts/GeistVF.woff", variable: "--font-geist-sans" });

export default function LandingPageLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-primary dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
