apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: nfs-client-provisioner
  # storageClassName: nfs-client-provisioner
