apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual # This is important for manual provisioning, Kubernetes won't use default dynamic provisioners
  capacity:
    storage: 10Gi # The storage capacity you want for the volume
  accessModes:
    - ReadWriteMany # Multiple pods can read/write to the volume
  hostPath:
    path: /data/postgresql # Path on the host machine
    type: DirectoryOrCreate # Ensure the directory exists or is created automatically

